# Generated by Django 4.1.3 on 2022-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('slug', models.CharField(help_text='This is a unique identifier. It should be Unique for every article', max_length=50, primary_key=True, serialize=False)),
                ('menu', models.CharField(choices=[('News', 'News'), ('Markets', 'Markets'), ('Politics', 'Politics'), ('Fiction-and-Poetry', 'Fiction and Poetry'), ('Books-and-Culture', 'Books and Culture'), ('Humour-and-Cartoons', 'Humour and Cartoons'), ('Puzzles-and-Games', 'Puzzles and Games'), ('Style', 'Style')], help_text='This are the menu items, Be cautious as it affects how the article is displayed in the front end', max_length=20)),
                ('article_category', models.CharField(blank=True, choices=[('MD', 'Market Data TSK Money'), ('CR', 'Commercial Real Estate'), ('CF', 'Commodities and Futures'), ('SJ', 'Stocks and Juacali'), ('D', 'Diplomacy '), ('ES', 'Eighty-Sixed'), ('CL', 'Courts and Law'), ('B', 'Books'), ('TM', 'TV and Music'), ('F', 'Food')], help_text='if the is no article category just leave blank', max_length=20, null=True)),
                ('article_name', models.CharField(help_text='Can be Same as the Slug', max_length=250)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('article_paragraph_1', models.CharField(blank=True, help_text='Input text for the first part here', max_length=1500)),
                ('article_paragraph_2', models.CharField(blank=True, help_text='Input text for the second part here', max_length=1500)),
                ('article_caption', models.CharField(max_length=25)),
                ('writer', models.CharField(blank=True, help_text="article writer's name", max_length=50)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='articlew',
            fields=[
                ('slug', models.CharField(help_text='This is a unique identifier. It should be Unique for every article', max_length=50, primary_key=True, serialize=False)),
                ('menu', models.CharField(choices=[('News', 'News'), ('Markets', 'Markets'), ('Politics', 'Politics'), ('Fiction-and-Poetry', 'Fiction and Poetry'), ('Books-and-Culture', 'Books and Culture'), ('Humour-and-Cartoons', 'Humour and Cartoons'), ('Puzzles-and-Games', 'Puzzles and Games'), ('Style', 'Style')], help_text='This are the menu items, Be cautious as it affects how the article is displayed in the front end', max_length=20)),
                ('article_category', models.CharField(blank=True, choices=[('MD', 'Market Data TSK Money'), ('CR', 'Commercial Real Estate'), ('CF', 'Commodities and Futures'), ('SJ', 'Stocks and Juacali'), ('D', 'Diplomacy '), ('ES', 'Eighty-Sixed'), ('CL', 'Courts and Law'), ('B', 'Books'), ('TM', 'TV and Music'), ('F', 'Food')], help_text='if the is no article category just leave blank', max_length=20, null=True)),
                ('article_name', models.CharField(help_text='Can be Same as the Slug', max_length=250)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('article_paragraph_1', models.CharField(blank=True, help_text='Input text for the first part here', max_length=1500)),
                ('article_paragraph_2', models.CharField(blank=True, help_text='Input text for the second part here', max_length=1500)),
                ('article_caption', models.CharField(max_length=25)),
                ('writer', models.CharField(blank=True, help_text="article writer's name", max_length=50)),
                ('recommended', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
