# Generated by Django 4.1.3 on 2022-11-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('Menu', models.CharField(choices=[('N', 'News'), ('M', 'Markets'), ('P', 'Politics'), ('FP', 'Fiction and Poetry'), ('BC', 'Books and Culture'), ('HC', 'Humour and Cartoons'), ('PG', 'Puzzles and Games'), ('S', 'Style')], max_length=20)),
                ('article_category', models.CharField(choices=[('MD', 'Market Data TSK Money'), ('CR', 'Commercial Real Estate'), ('CF', 'Commodities and Futures'), ('SJ', 'Stocks and Juacali'), ('D', 'Diplomacy '), ('ES', 'Eighty-Sixed'), ('CL', 'Courts and Law'), ('B', 'Books'), ('TM', 'TV and Music'), ('F', 'Food')], max_length=20)),
                ('article_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
