# Generated by Django 4.1.3 on 2022-11-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_of_kiambu_backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='articlew',
        ),
    ]
