# Generated by Django 4.1.3 on 2022-11-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_of_kiambu_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.CharField(default=1, help_text='To separate paragraphs, use the tag <br> between to represent a space between the paragraphs', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='Menu',
            field=models.CharField(choices=[('N', 'News'), ('M', 'Markets'), ('P', 'Politics'), ('FP', 'Fiction and Poetry'), ('BC', 'Books and Culture'), ('HC', 'Humour and Cartoons'), ('PG', 'Puzzles and Games'), ('S', 'Style')], help_text='This are the menu items, Be cautious as it affects how the article is displayed in the front end', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(blank=True, choices=[('MD', 'Market Data TSK Money'), ('CR', 'Commercial Real Estate'), ('CF', 'Commodities and Futures'), ('SJ', 'Stocks and Juacali'), ('D', 'Diplomacy '), ('ES', 'Eighty-Sixed'), ('CL', 'Courts and Law'), ('B', 'Books'), ('TM', 'TV and Music'), ('F', 'Food')], help_text='if the is no article category just leave blank', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(help_text='This is a unique identifier. It should be Unique for every article', max_length=50, primary_key=True, serialize=False),
        ),
    ]
