# Generated by Django 4.1.3 on 2022-11-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_of_kiambu_backend', '0002_remove_article_id_article_article_alter_article_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Menu',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(help_text='Can be Same as the Slug', max_length=250),
        ),
    ]
