# Generated by Django 4.1.3 on 2022-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_of_kiambu_backend', '0003_rename_menu_article_menu_alter_article_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='menu',
            field=models.CharField(choices=[('News', 'News'), ('Markets', 'Markets'), ('Politics', 'Politics'), ('Fiction-and-Poetry', 'Fiction and Poetry'), ('Books-and-Culture', 'Books and Culture'), ('Humour-and-Cartoons', 'Humour and Cartoons'), ('Puzzles-and-Games', 'Puzzles and Games'), ('Style', 'Style')], help_text='This are the menu items, Be cautious as it affects how the article is displayed in the front end', max_length=20),
        ),
    ]
